import type { Object3D, Material } from "three";
import type { ThreeElements } from "@react-three/fiber";
import type { JSX } from "react/jsx-runtime";

export interface GLTFResult {
  nodes: {
    [key: string]: Object3D;
  };
  materials: {
    [key: string]: Material;
  };
}

/**
 * The props to be passed to a model component
 * generated by GLTJSX
 */
export type ModelProps = {
  distance: "near" | "mid" | "far";
} & ThreeElements["group"];

/**
 * The three-part decimated model produced by `lib/modelFactory`,
 * to be used in rendering alongside `@react-three/drei/Detailed`
 */
export type DecimatedModel = {
  near: (props?: ThreeElements["group"]) => JSX.Element;
  mid: (props?: ThreeElements["group"]) => JSX.Element;
  far: (props?: ThreeElements["group"]) => JSX.Element;
};

